version: "3.9"

services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # на хосте 8000, внутри контейнера 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5433:5432"  # изменил порт на хосте, чтобы избежать конфликта с локальной БД